apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  namespace: dev
spec:
  containers:
    - name: busybox-container
      image: busybox:latest
      command: ["sleep", "3600"]  # Example command: sleep for 3600 seconds
