apiVersion: v1
kind: Pod
metadata:
  name: example-pod-1
spec:
  containers:
    - name: my-container
      image: nginx
      volumeMounts:
        - name: emptydir-volume
          mountPath: /tmp
  volumes:
    - name: emptydir-volume
      emptyDir: {}
