apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  namespace: dev
  labels:
    app: example-app
spec:
  containers:
    - name: main-container
      image: nginx:latest
      ports:
        - containerPort: 80

