apiVersion: v1
kind: LimitRange
metadata:
  name: my-limit-range
  namespace: labs
spec:
  limits:
    - type: Container
      max:
        cpu: "2"
        memory: 1Gi
      min:
        cpu: "0.1"
        memory: 100Mi
      default:
        cpu: "1"
        memory: 512Mi
      defaultRequest:
        cpu: "0.5"
        memory: 256Mi
      maxLimitRequestRatio:
        cpu: "4"
        memory: "2"
