apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaiset1
spec:
  replicas: 3
  selector:
    matchExpressions:
    - {key: environment, operator: In, values: [production, staging]}
  template:
    metadata:
      labels:
        app: my-app
        environment: production
    spec:
      containers:
      - name: my-container
        image: amitow/nginx:v1

