apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pod-anti-affinity
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - db
        topologyKey: kubernetes.io/hostname
  containers:
  - name: apache-container
    image: httpd
