apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pod-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - db
        topologyKey: kubernetes.io/hostname
  containers:
  - name: nginx-container
    image: nginx
