apiVersion: v1
kind: Pod
metadata:
  name: readiness-failure
spec:
  containers:
    - name: failing-app
      image: busybox
      args:
        - /bin/sh
        - -c
        - |
          echo 'Starting container...'; 
          #          sleep 60;  # ⏳ Wait 60 seconds before creating the file
          touch /tmp/ready; 
          echo 'Application is now ready'; 
          sleep 300;

      readinessProbe:
        exec:
          command:
            - ls
            - /tmp/ready  # ❌ This file doesn't exist for 60 seconds, probe fails
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 3  # After 3 failures, pod stays unready

