apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-dep
spec:
  replicas: 3
  selector:
    app: hello-dep
  template:
    metadata:
      labels:
        app: hello-dep
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged 
        imagePullPolicy: Always
        name: hello-dep
        ports:
        - containerPort: 8080
