apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resource-quota
  namespace: labs
spec:
  hard:
    pods: "5"
    requests.cpu: "2"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 4Gi
