apiVersion: v1
kind: Pod
metadata:
  name: startup-failure
spec:
  containers:
    - name: failing-app
      image: busybox
      args:
        - /bin/sh
        - -c
        - "echo 'Starting...'; sleep 300"  # No /tmp/healthy file is created

      startupProbe:
        exec:
          command:
            - ls
            - /tmp/healthy  # This file does NOT exist, causing failure
        failureThreshold: 5   # After 5 failures, restart the container
        periodSeconds: 5      # Probe runs every 5 seconds

